[package]
name = "sliru-tools"
version = "0.1.0"
edition = "2024"

[lib]
name = "sliru_tools_lib"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "sliru_tools"
path = "src/main.rs"

[dependencies]
slint = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
csv = "1"
yaml-rust2 = "0.10"
quick-xml = "0.38"

[build-dependencies]
slint-build = "1"
